spring.application.name=indexing-service

server.port=8081
server.servlet.context-path=/

logging.level.root=INFO
logging.level.index=INFO
logging.level.metadata=INFO
logging.level.api=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# MongoDB Configuration
mongodb.connection-string=mongodb://localhost:27017/
mongodb.inverted-index.database=inverted_index
mongodb.inverted-index.collection=words
mongodb.metadata.database=metadata
mongodb.metadata.collection=books

# Datalake Configuration
datalake.base-path=../datalake/