server.port=8082
spring.application.name=search-service

mongodb.uri=mongodb://localhost:27017/
mongodb.inverted-index.database=inverted_index
mongodb.inverted-index.collection=words
mongodb.metadata.database=metadata
mongodb.metadata.collection=books

logging.level.com.thebiggestdata.searchservice=INFO
logging.level.org.springframework.web=INFO

management.endpoints.web.exposure.include=health info
management.endpoint.health.show-details=always

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method